version: '3'

services:
  app:
    image: python:3.10
    volumes:
      - "./:/opt/aweber"
    ports:
      - "9000:9000"
    command: "/opt/aweber/docker/go.sh"

  tester:
    image: frolvlad/alpine-bash
    volumes:
      - "./docker/tester.sh:/opt/aweber/docker/tester.sh"
    depends_on:
      - "app"
    command: "/opt/aweber/docker/tester.sh"

# vim: set ts=2 sw=2 et ai:
