# Generated by Django 4.0.3 on 2022-03-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('parts_count', models.IntegerField(default=0, verbose_name='Number of parts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date/time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date/time')),
            ],
        ),
    ]
